// lib/citiesData.js
// Data source for the city service-area pages served by
// app/service-areas/[slug]/page.js. Each town has genuinely unique local
// content: correct county, the real county disposal facility, its actual
// relationship to Lake Lanier, real landmarks, and town-specific FAQs. This
// is deliberate: thin "[service] in [city]" template pages get penalized, so
// every page here earns its place with distinct, accurate local detail.
// Add a town by adding an object; the route and sitemap pick it up.

export const cities = {
  'gainesville': {
    slug: 'gainesville', name: 'Gainesville', countyLabel: 'Hall County',
    region: 'North Georgia', zip: '30501',
    metaTitle: 'Junk Removal & Dumpster Rental in Gainesville, GA',
    metaDescription: 'Junk removal and dumpster rental in Gainesville, GA. Same-week pickup, flat pricing, and local crews who know Hall County. From downtown to the Lake District.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN GAINESVILLE.',
    sub: 'Same-week hauling and driveway dumpsters across the Queen City of the Mountains, from the historic square to the shores of Lake Lanier.',
    lakeContext: 'Gainesville sits on the northeast shore of Lake Lanier, so lake-house cleanouts, dock-season purges, and storm debris are a big part of what we handle here.',
    intro: 'Gainesville is the seat of Hall County and the hub of northeast Georgia, the Poultry Capital of the World and the Queen City of the Mountains. From century-old homes off Green Street to new townhomes in the Lake District, we haul junk and drop dumpsters all over town.',
    localAngle: 'The mix of historic housing stock downtown and fast new construction near the lake keeps us busy with everything from single-item furniture pickups to full estate cleanouts. When a Green Street bungalow changes hands or a lake house gets a refresh, we are the local call.',
    areas: ['Downtown Square', 'Green Street historic district', 'The Lake District', 'New Holland', 'Jesse Jewell Parkway corridor', 'Midtown & Lakeshore', 'Chicopee'],
    disposal: 'As a Hall County hauler, we take local loads to the Hall County Landfill on Oakbrook Drive, which accepts only Hall-County-generated waste, and route donations and recyclables first.',
    distance: 'Right in the heart of Hall County on I-985 and GA-365, about 52 miles northeast of Atlanta.',
    faqs: [
      { q: 'Do you offer junk removal in downtown Gainesville?', a: 'Yes. We cover the whole city, from the historic square and Green Street to the Lake District and the Jesse Jewell corridor. Stairs and older homes are no problem, we carry it all out.' },
      { q: 'Where does my junk go after pickup in Gainesville?', a: 'We sort every load. Usable items go to local donation partners, metal and electronics go to recyclers, and true trash goes to the Hall County Landfill on Oakbrook Drive, which takes Hall-County waste.' },
      { q: 'Can you handle a lake house cleanout on Lanier?', a: 'Absolutely. Lake-house cleanouts, dock-season purges, and storm debris are common jobs for us around the Gainesville shoreline. Send photos and we quote a flat price.' },
    ],
    nearby: [{ slug: 'oakwood', label: 'Oakwood' }, { slug: 'flowery-branch', label: 'Flowery Branch' }, { slug: 'clermont', label: 'Clermont' }, { slug: 'murrayville', label: 'Murrayville' }],
  },

  'flowery-branch': {
    slug: 'flowery-branch', name: 'Flowery Branch', countyLabel: 'Hall County',
    region: 'North Georgia', zip: '30542',
    metaTitle: 'Junk Removal & Dumpster Rental in Flowery Branch, GA',
    metaDescription: 'Junk removal and dumpster rental in Flowery Branch, GA. Flat pricing, same-week pickup, and local crews. From Old Town to the Gaines Ferry lakefront.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN FLOWERY BRANCH.',
    sub: 'Same-week hauling and driveway dumpsters across South Hall, from historic Old Town to the lakefront off Gaines Ferry Road.',
    lakeContext: 'Flowery Branch has one of the only historic downtowns in Georgia that sits right on Lake Lanier, so waterfront cleanouts and lake-season hauls are part of our regular week here.',
    intro: 'Flowery Branch is a South Hall railroad town turned lakeside community, home to the Atlanta Falcons training complex and a preserved Old Town on the shore of Lake Lanier. We haul junk and drop dumpsters from the Spout Springs subdivisions to the Gaines Ferry lakefront.',
    localAngle: 'Steady new construction along Spout Springs plus established lakefront homes off Gaines Ferry means we see it all here, remodel debris from a growing subdivision one day, a full lake-house furniture haul the next.',
    areas: ['Old Town / historic downtown', 'Gaines Ferry Road lakefront', 'Spout Springs corridor', 'Sterling on the Lake', 'McEver Road', 'Van Pugh & Old Federal park areas'],
    disposal: 'Flowery Branch loads go to the Hall County Landfill on Oakbrook Drive in Gainesville, which accepts only Hall-County-generated waste. We route donations and recycling first.',
    distance: 'On the eastern shore of Lake Lanier off I-985, about 45 miles north of Atlanta and 12 miles south of Gainesville.',
    faqs: [
      { q: 'Do you serve the Gaines Ferry and lakefront areas of Flowery Branch?', a: 'Yes. The Gaines Ferry lakefront is one of our regular areas. We handle lake-house cleanouts, furniture removal, and dock-season debris throughout the Flowery Branch shoreline.' },
      { q: 'Can you drop a dumpster in a Spout Springs neighborhood?', a: 'We can. Driveway-friendly roll-offs are ideal for the newer Spout Springs subdivisions, whether it is a remodel, a flooring tear-out, or a garage cleanout. We size it to the project.' },
      { q: 'How fast can you get to Flowery Branch?', a: 'Flowery Branch is in our core service area, so same-week and often next-day pickups are the norm. Send a photo of what you need gone for a fast flat quote.' },
    ],
    nearby: [{ slug: 'oakwood', label: 'Oakwood' }, { slug: 'buford', label: 'Buford' }, { slug: 'gainesville', label: 'Gainesville' }],
  },

  'oakwood': {
    slug: 'oakwood', name: 'Oakwood', countyLabel: 'Hall County',
    region: 'North Georgia', zip: '30566',
    metaTitle: 'Junk Removal & Dumpster Rental in Oakwood, GA',
    metaDescription: 'Junk removal and dumpster rental in Oakwood, GA. Flat pricing, same-week pickup, local Hall County crews. From Mundy Mill to the UNG Gainesville campus area.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN OAKWOOD.',
    sub: 'Same-week hauling and driveway dumpsters along the I-985 gateway, from Mundy Mill to Thurmon Tanner Parkway.',
    lakeContext: 'Oakwood sits just off Lake Lanier between Gainesville and Flowery Branch, close enough that lake-season cleanouts and nearby waterfront hauls are common.',
    intro: 'Oakwood is a fast-growing, service-centered Hall County city on I-985, the gateway toward Road Atlanta and Chateau Elan and home to a University of North Georgia campus. We haul junk and drop dumpsters from Mundy Mill to the Thurmon Tanner corridor.',
    localAngle: 'With the UNG campus, growing subdivisions like Mundy Mill, and busy commercial corridors, Oakwood keeps us moving on student move-outs, apartment turns, and household cleanouts alike.',
    areas: ['Mundy Mill', 'Thurmon Tanner Parkway', 'UNG Gainesville campus area', 'Chicopee Woods', 'Mcever Road corridor', 'I-985 gateway'],
    disposal: 'Oakwood loads go to the Hall County Landfill on Oakbrook Drive, which accepts only Hall-County waste, with donations and recyclables pulled out first.',
    distance: 'On I-985 just south of Gainesville, about 48 miles north of Atlanta.',
    faqs: [
      { q: 'Do you handle student move-outs near the UNG Oakwood campus?', a: 'Yes. Move-outs, apartment turns, and dorm-style cleanouts near the University of North Georgia campus are common jobs. We haul furniture, mattresses, and leftover junk in one trip.' },
      { q: 'Can you serve the Mundy Mill area?', a: 'We do. Mundy Mill and the surrounding Oakwood subdivisions are in our core area, whether you need a single-item pickup, a garage cleanout, or a driveway dumpster.' },
      { q: 'Where does Oakwood junk get taken?', a: 'Trash goes to the Hall County Landfill on Oakbrook Drive in Gainesville. Before that, we route anything usable to local donation partners and recycle metal and electronics.' },
    ],
    nearby: [{ slug: 'gainesville', label: 'Gainesville' }, { slug: 'flowery-branch', label: 'Flowery Branch' }, { slug: 'buford', label: 'Buford' }],
  },

  'buford': {
    slug: 'buford', name: 'Buford', countyLabel: 'Gwinnett & Hall Counties',
    region: 'North Georgia', zip: '30518',
    metaTitle: 'Junk Removal & Dumpster Rental in Buford, GA',
    metaDescription: 'Junk removal and dumpster rental in Buford, GA. Flat pricing, same-week pickup. From the Mall of Georgia to the Lanier shoreline at Buford Dam.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN BUFORD.',
    sub: 'Same-week hauling and driveway dumpsters across the Gwinnett-Hall line, from the Mall of Georgia to the lake at Buford Dam.',
    lakeContext: 'Buford sits at the southern tip of Lake Lanier right at Buford Dam, so lakeside cleanouts and dock-season hauls near the shoreline are a regular part of our work here.',
    intro: 'Buford straddles the Gwinnett-Hall county line, with most of the city in northern Gwinnett and a sliver in southern Hall. It anchors the Mall of Georgia area and reaches the lake at Buford Dam. We haul junk and drop dumpsters across both county sides.',
    localAngle: 'Buford mixes historic downtown homes, dense newer subdivisions near the Mall of Georgia, and lakeside properties at the dam, so we handle everything from single-item pickups to full renovation dumpsters and lake-house cleanouts.',
    areas: ['Mall of Georgia area', 'Historic downtown Buford / Main Street', 'Lanier Harbor & Buford Dam shoreline', 'Hamilton Mill area', 'Ivy Creek', 'Sardis / Friendship Road corridor'],
    disposal: 'Buford spans two counties, so disposal depends on where you are. We route usable items to donation and recycling first, then take trash to the correct county facility for your address.',
    distance: 'At the south end of Lake Lanier off I-985 and I-85, about 30 miles north of Atlanta.',
    faqs: [
      { q: 'Do you serve both the Gwinnett and Hall sides of Buford?', a: 'Yes. Buford straddles the county line and we cover the whole city, from the Mall of Georgia area in Gwinnett to the Hall County shoreline near Buford Dam.' },
      { q: 'Can you do a lake-house cleanout near Buford Dam?', a: 'Absolutely. The southern tip of Lake Lanier at Buford Dam is right in our area. We handle lake-house furniture removal, dock-season purges, and storm debris.' },
      { q: 'How much is junk removal in Buford?', a: 'It is priced by how much fills the truck, from a single item to a full load, always confirmed as a flat number up front. Our pricing guide breaks down the ranges.' },
    ],
    nearby: [{ slug: 'flowery-branch', label: 'Flowery Branch' }, { slug: 'suwanee', label: 'Suwanee' }, { slug: 'braselton', label: 'Braselton' }],
  },

  'braselton': {
    slug: 'braselton', name: 'Braselton', countyLabel: 'Jackson, Hall, Gwinnett & Barrow Counties',
    region: 'North Georgia', zip: '30517',
    metaTitle: 'Junk Removal & Dumpster Rental in Braselton, GA',
    metaDescription: 'Junk removal and dumpster rental in Braselton, GA. Flat pricing, same-week pickup. From Chateau Elan to the Highway 211 growth corridor.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN BRASELTON.',
    sub: 'Same-week hauling and driveway dumpsters across the four-county town, from Chateau Elan to the Highway 211 corridor.',
    lakeContext: null,
    intro: 'Braselton is one of Georgia\u2019s rare four-county towns, spanning Jackson, Hall, Gwinnett, and Barrow, and home to Chateau Elan Winery & Resort and a Northeast Georgia Medical Center campus. We haul junk and drop dumpsters across every corner of it.',
    localAngle: 'Braselton\u2019s explosive growth around Chateau Elan and the Highway 211 corridor means constant new construction, subdivision remodels, and move-ins, which is exactly when a driveway dumpster or a quick junk haul earns its keep.',
    areas: ['Chateau Elan area', 'Downtown Braselton / Mill Street', 'Highway 211 corridor', 'Northeast Georgia Medical Center Braselton area', 'Spout Springs Road', 'Cresswind & area subdivisions'],
    disposal: 'Because Braselton sits in four counties, disposal depends on your exact address. We donate and recycle what we can, then route trash to the correct county facility.',
    distance: 'Along I-85 in the northeast metro, about 50 miles from Atlanta, straddling four counties.',
    faqs: [
      { q: 'Which counties does Braselton cover?', a: 'Braselton is unusual: it spans Jackson, Hall, Gwinnett, and Barrow counties. We serve the whole town and route disposal to the right county facility for your specific address.' },
      { q: 'Do you serve the Chateau Elan area?', a: 'Yes. The Chateau Elan communities and the surrounding Highway 211 corridor are a busy part of our service area for cleanouts, remodel debris, and dumpster rentals.' },
      { q: 'Can you handle new-construction debris in Braselton?', a: 'We can. With Braselton growing fast, we handle construction and renovation debris both as full-service hauls and with roll-off dumpsters you load on your own schedule.' },
    ],
    nearby: [{ slug: 'hoschton', label: 'Hoschton' }, { slug: 'buford', label: 'Buford' }, { slug: 'jefferson', label: 'Jefferson' }],
  },

  'cumming': {
    slug: 'cumming', name: 'Cumming', countyLabel: 'Forsyth County',
    region: 'North Georgia', zip: '30040',
    metaTitle: 'Junk Removal & Dumpster Rental in Cumming, GA',
    metaDescription: 'Junk removal and dumpster rental in Cumming, GA. Flat pricing, same-week pickup. From Cumming City Center to the Lake Lanier shoreline and Sawnee Mountain.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN CUMMING.',
    sub: 'Same-week hauling and driveway dumpsters across Forsyth County, from the GA-400 corridor to the west shore of Lake Lanier.',
    lakeContext: 'Cumming controls much of the western and southwestern shoreline of Lake Lanier, so lakeside cleanouts and dock-season hauls around parks like Mary Alice are a regular part of our week.',
    intro: 'Cumming is the only incorporated city in Forsyth County, one of the fastest-growing counties in the country, sitting on the west side of Lake Lanier along the GA-400 corridor. We haul junk and drop dumpsters from Cumming City Center to the lake.',
    localAngle: 'Forsyth\u2019s relentless growth means new subdivisions, remodels, and move-ins all over Cumming, plus established lakefront homes on the west shore, so we stay busy with everything from renovation dumpsters to lake-house furniture hauls.',
    areas: ['Cumming City Center', 'The Collection at Forsyth', 'Sawnee Mountain Preserve area', 'GA-400 corridor', 'Vickery', 'Mary Alice Park & west-shore lakefront'],
    disposal: 'Cumming loads are handled through Forsyth County\u2019s solid waste system, with the county landfill off Keith Bridge Road. We route donations and recyclables first.',
    distance: 'On the west side of Lake Lanier along GA-400, about 40 miles north of Atlanta.',
    faqs: [
      { q: 'Do you serve the Lake Lanier west shore around Cumming?', a: 'Yes. Cumming holds much of the lake\u2019s western shoreline, and lakeside cleanouts, furniture removal, and dock-season debris around areas like Mary Alice Park are regular jobs for us.' },
      { q: 'Can you drop a dumpster for a remodel in Forsyth County?', a: 'We can. With so much new construction and remodeling in Cumming, driveway roll-offs are popular here. We size the box to your project and set tonnage up front.' },
      { q: 'Where does Cumming junk go?', a: 'Trash is handled through Forsyth County\u2019s system and the landfill off Keith Bridge Road. Before that, we donate usable items and recycle metal and electronics.' },
    ],
    nearby: [{ slug: 'dawsonville', label: 'Dawsonville' }, { slug: 'buford', label: 'Buford' }, { slug: 'suwanee', label: 'Suwanee' }],
  },

  'suwanee': {
    slug: 'suwanee', name: 'Suwanee', countyLabel: 'Gwinnett County',
    region: 'North Georgia', zip: '30024',
    metaTitle: 'Junk Removal & Dumpster Rental in Suwanee, GA',
    metaDescription: 'Junk removal and dumpster rental in Suwanee, GA. Flat pricing, same-week pickup. From Suwanee Town Center to the Peachtree Industrial corridor.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN SUWANEE.',
    sub: 'Same-week hauling and driveway dumpsters across north Gwinnett, from Suwanee Town Center to the I-85 corridor.',
    lakeContext: 'Suwanee sits just south of Lake Lanier, close enough that lake-adjacent cleanouts and weekend-project hauls are common alongside its suburban neighborhoods.',
    intro: 'Suwanee is a polished north Gwinnett suburb known for Suwanee Town Center and a string of award-winning parks, just off I-85 and a short hop from Lake Lanier. We haul junk and drop dumpsters across its neighborhoods and busy corridors.',
    localAngle: 'Suwanee\u2019s mature swim-and-tennis subdivisions generate steady demand for garage cleanouts, furniture removal, and remodel debris, while its commercial corridors keep us busy with office and retail turns.',
    areas: ['Suwanee Town Center', 'Old Town Suwanee', 'Sims Lake Park area', 'Peachtree Industrial corridor', 'Lawrenceville-Suwanee Road', 'I-85 & Suwanee Dam Road'],
    disposal: 'Suwanee sits in Gwinnett County, where disposal runs through the county\u2019s transfer and hauling network. We donate and recycle what we can before anything is disposed of.',
    distance: 'Off I-85 in north Gwinnett, about 33 miles northeast of Atlanta.',
    faqs: [
      { q: 'Do you handle garage and basement cleanouts in Suwanee?', a: 'Yes. Suwanee\u2019s established swim-and-tennis neighborhoods keep us busy with garage and basement cleanouts, furniture removal, and full-home decluttering. We do the lifting.' },
      { q: 'Can you serve the Suwanee Town Center area?', a: 'We cover all of Suwanee, from Town Center and Old Town to the subdivisions off Lawrenceville-Suwanee Road and the Peachtree Industrial corridor.' },
      { q: 'Do you rent dumpsters for Suwanee remodels?', a: 'We do. Driveway roll-offs are ideal for Suwanee remodels and cleanouts, sized to your project with tonnage and flat pricing set up front.' },
    ],
    nearby: [{ slug: 'buford', label: 'Buford' }, { slug: 'cumming', label: 'Cumming' }, { slug: 'braselton', label: 'Braselton' }],
  },

  'dawsonville': {
    slug: 'dawsonville', name: 'Dawsonville', countyLabel: 'Dawson County',
    region: 'North Georgia', zip: '30534',
    metaTitle: 'Junk Removal & Dumpster Rental in Dawsonville, GA',
    metaDescription: 'Junk removal and dumpster rental in Dawsonville, GA. Flat pricing, same-week pickup. From the North Georgia Premium Outlets to the Chestatee lake arm.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN DAWSONVILLE.',
    sub: 'Same-week hauling and driveway dumpsters across Dawson County, from the GA-400 outlets to the northern arm of Lake Lanier.',
    lakeContext: 'The Chestatee River arm of Lake Lanier reaches into southern Dawson County, so lakeside cleanouts near the quieter northern end of the lake are part of our work here.',
    intro: 'Dawsonville is the seat of Dawson County and the \u201cGateway to the Mountains,\u201d anchored by the North Georgia Premium Outlets on GA-400 with Amicalola Falls and the Blue Ridge foothills just beyond. We haul junk and drop dumpsters across it.',
    localAngle: 'Dawsonville blends lake homes on the Chestatee arm, mountain-adjacent properties, and steady new growth along GA-400, so we handle everything from cabin cleanouts to renovation dumpsters to lake-house furniture hauls.',
    areas: ['North Georgia Premium Outlets area', 'Downtown Dawsonville', 'GA-400 corridor', 'Chestatee River lake arm', 'Kelly Bridge & Chestatee Road', 'War Hill Park area'],
    disposal: 'Dawsonville loads are handled through Dawson County\u2019s solid waste system, with the county landfill off Burnt Stand Road. Donations and recycling come first.',
    distance: 'At the north end of the GA-400 corridor, about 60 miles north of Atlanta and 20 miles west of Gainesville.',
    faqs: [
      { q: 'Do you serve the lake areas on the Dawsonville side of Lanier?', a: 'Yes. The Chestatee River arm of Lake Lanier reaches into Dawson County, and lakeside cleanouts and furniture hauls on that quieter north end of the lake are regular jobs for us.' },
      { q: 'Can you handle a mountain cabin cleanout near Dawsonville?', a: 'We can. Cabin and mountain-property cleanouts around Dawsonville and the Amicalola foothills are common, from a single-room clear to a full haul.' },
      { q: 'Where does Dawsonville junk get taken?', a: 'Trash goes through Dawson County\u2019s system and the landfill off Burnt Stand Road. Before that, we donate usable items and recycle metal and electronics.' },
    ],
    nearby: [{ slug: 'cumming', label: 'Cumming' }, { slug: 'dahlonega', label: 'Dahlonega' }, { slug: 'gainesville', label: 'Gainesville' }],
  },

  'clermont': {
    slug: 'clermont', name: 'Clermont', countyLabel: 'Hall County',
    region: 'North Georgia', zip: '30527',
    metaTitle: 'Junk Removal & Dumpster Rental in Clermont, GA',
    metaDescription: 'Junk removal and dumpster rental in Clermont, GA. Flat pricing, same-week pickup, local Hall County crews. Small-town service in the North Hall foothills.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN CLERMONT.',
    sub: 'Same-week hauling and driveway dumpsters for the small North Hall town in the Blue Ridge foothills.',
    lakeContext: null,
    intro: 'Clermont is a small, quiet town in the northern part of Hall County, tucked into the Blue Ridge foothills near Wauka Mountain north of Gainesville. We bring the same flat pricing and same-week service to Clermont that we bring to the bigger towns.',
    localAngle: 'Clermont\u2019s rural properties, older farmhouses, and wooded lots mean we handle a lot of shed teardowns, yard and storm debris, barn cleanouts, and the kind of hauls that neighbors out here would otherwise have to make repeated trips for.',
    areas: ['Downtown Clermont', 'Wauka Mountain area', 'North Hall / GA-283 corridor', 'Blue Ridge foothills properties', 'Clermont-area farms & wooded lots'],
    disposal: 'Clermont loads go to the Hall County Landfill on Oakbrook Drive in Gainesville, which accepts only Hall-County-generated waste. We donate and recycle first.',
    distance: 'In the North Hall foothills, about 10 miles north of Gainesville.',
    faqs: [
      { q: 'Do you really serve a small town like Clermont?', a: 'Yes. Clermont is part of our North Hall service area, and we bring the same flat pricing and same-week service here as anywhere else, no rural surcharge games.' },
      { q: 'Can you tear down an old shed or barn in Clermont?', a: 'We can. Shed and structure teardowns, plus barn and property cleanouts, are common out here. We demo it and haul every piece, leaving the spot clear.' },
      { q: 'Do you haul storm and yard debris in the Clermont area?', a: 'Yes. After a North Georgia storm, we clear fallen limbs, brush, and debris that curbside pickup will not take, so your property is usable again fast.' },
    ],
    nearby: [{ slug: 'gainesville', label: 'Gainesville' }, { slug: 'murrayville', label: 'Murrayville' }, { slug: 'lula', label: 'Lula' }],
  },

  'lula': {
    slug: 'lula', name: 'Lula', countyLabel: 'Hall County',
    region: 'North Georgia', zip: '30554',
    metaTitle: 'Junk Removal & Dumpster Rental in Lula, GA',
    metaDescription: 'Junk removal and dumpster rental in Lula, GA. Flat pricing, same-week pickup, local Hall County crews. Small-town service in the northeast Hall foothills.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN LULA.',
    sub: 'Same-week hauling and driveway dumpsters for the heritage railroad town in northeast Hall County.',
    lakeContext: null,
    intro: 'Lula is a heritage-minded railroad town in the more mountainous northeastern corner of Hall County, known for its spring Railroad Days festival. We bring flat pricing and same-week hauling to Lula the same as anywhere in the county.',
    localAngle: 'Lula\u2019s older homes, rural acreage, and railroad-town character mean we see a lot of property cleanouts, shed and outbuilding teardowns, and yard debris hauls, the jobs that are a real hassle without a truck and a crew.',
    areas: ['Downtown Lula', 'GA-365 corridor', 'Belton area', 'Northeast Hall acreage', 'Lula-area farms & older homes'],
    disposal: 'Lula loads go to the Hall County Landfill on Oakbrook Drive in Gainesville, which takes only Hall-County-generated waste. Donations and recycling come first.',
    distance: 'In the northeast corner of Hall County along GA-365, about 15 miles from Gainesville.',
    faqs: [
      { q: 'Do you serve Lula and northeast Hall County?', a: 'Yes. Lula is part of our Hall County service area, with the same flat pricing and same-week service we offer in Gainesville, no rural runaround.' },
      { q: 'Can you clear out an old property or outbuilding in Lula?', a: 'We can. Property cleanouts, shed and outbuilding teardowns, and acreage hauls are common in the Lula area. We demo, load, and haul it all.' },
      { q: 'Do you take yard and storm debris around Lula?', a: 'Yes. Branches, brush, and storm debris that are too big for curbside pickup are exactly what we haul, so your property is clear and usable again.' },
    ],
    nearby: [{ slug: 'gainesville', label: 'Gainesville' }, { slug: 'clermont', label: 'Clermont' }, { slug: 'murrayville', label: 'Murrayville' }],
  },

  'murrayville': {
    slug: 'murrayville', name: 'Murrayville', countyLabel: 'Hall County',
    region: 'North Georgia', zip: '30564',
    metaTitle: 'Junk Removal & Dumpster Rental in Murrayville, GA',
    metaDescription: 'Junk removal and dumpster rental in Murrayville, GA. Flat pricing, same-week pickup, local Hall County crews. Service across the North Hall community.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN MURRAYVILLE.',
    sub: 'Same-week hauling and driveway dumpsters for the North Hall community along the US-129 corridor.',
    lakeContext: null,
    intro: 'Murrayville is a rural North Hall community along the US-129 and GA-60 corridor between Gainesville and the mountains toward Dahlonega. We bring the same flat pricing and same-week hauling here that we bring to town.',
    localAngle: 'Murrayville\u2019s larger lots, farms, and country properties mean we handle plenty of acreage cleanouts, shed and structure teardowns, and yard debris, the hauls that would otherwise mean many trips in a pickup you do not want to load.',
    areas: ['US-129 corridor', 'GA-60 / Thompson Bridge Road', 'North Hall community', 'Chestatee area', 'Murrayville-area farms & acreage'],
    disposal: 'Murrayville loads go to the Hall County Landfill on Oakbrook Drive in Gainesville, which accepts only Hall-County-generated waste. We donate and recycle first.',
    distance: 'In North Hall along US-129, between Gainesville and the mountains toward Dahlonega.',
    faqs: [
      { q: 'Do you serve the Murrayville community?', a: 'Yes. Murrayville and the North Hall corridor are part of our regular service area, with the same flat pricing and same-week service as the rest of Hall County.' },
      { q: 'Can you handle an acreage or property cleanout in Murrayville?', a: 'We can. Larger-lot and farm-property cleanouts, shed teardowns, and outbuilding clears are common out here. We bring the truck and the crew so you are not making trip after trip.' },
      { q: 'Do you haul yard and storm debris around Murrayville?', a: 'Yes. Fallen limbs, brush, and storm debris that curbside will not take are regular hauls for us, clearing your property fast.' },
    ],
    nearby: [{ slug: 'gainesville', label: 'Gainesville' }, { slug: 'clermont', label: 'Clermont' }, { slug: 'dahlonega', label: 'Dahlonega' }],
  },

  'dahlonega': {
    slug: 'dahlonega', name: 'Dahlonega', countyLabel: 'Lumpkin County',
    region: 'North Georgia', zip: '30533',
    metaTitle: 'Junk Removal & Dumpster Rental in Dahlonega, GA',
    metaDescription: 'Junk removal and dumpster rental in Dahlonega, GA. Flat pricing, same-week pickup. From the historic gold-rush square to North Georgia wine country.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN DAHLONEGA.',
    sub: 'Same-week hauling and driveway dumpsters across Lumpkin County, from the historic square to the wine-country hills.',
    lakeContext: null,
    intro: 'Dahlonega is the seat of Lumpkin County, site of the first major U.S. gold rush and home to the University of North Georgia, with a historic square that anchors North Georgia\u2019s wine country. We haul junk and drop dumpsters across the area.',
    localAngle: 'Dahlonega mixes a busy college town, historic homes around the square, mountain cabins, and vineyard properties, so we handle student move-outs, cabin cleanouts, remodel debris, and the occasional winery or event haul.',
    areas: ['Historic Dahlonega Square', 'University of North Georgia area', 'GA-400 / GA-60 corridor', 'North Georgia wine country', 'Auraria', 'Mountain cabin & vineyard properties'],
    disposal: 'Dahlonega loads are handled through Lumpkin County\u2019s solid waste system. We route usable items to donation and recycle metal and electronics before anything is disposed of.',
    distance: 'In the Blue Ridge foothills at the north end of GA-400, about 65 miles north of Atlanta.',
    faqs: [
      { q: 'Do you handle student move-outs near UNG in Dahlonega?', a: 'Yes. Move-outs and apartment turns near the University of North Georgia are common, and we haul furniture, mattresses, and leftover junk in a single trip.' },
      { q: 'Can you clear a mountain cabin near Dahlonega?', a: 'We can. Cabin and mountain-property cleanouts around Dahlonega and the surrounding wine country are regular jobs, from a single-room clear to a full haul.' },
      { q: 'Do you serve Lumpkin County?', a: 'Yes. Dahlonega and the surrounding Lumpkin County area are in our service range, with flat pricing and the same care we bring everywhere.' },
    ],
    nearby: [{ slug: 'dawsonville', label: 'Dawsonville' }, { slug: 'murrayville', label: 'Murrayville' }, { slug: 'cumming', label: 'Cumming' }],
  },

  'jefferson': {
    slug: 'jefferson', name: 'Jefferson', countyLabel: 'Jackson County',
    region: 'North Georgia', zip: '30549',
    metaTitle: 'Junk Removal & Dumpster Rental in Jefferson, GA',
    metaDescription: 'Junk removal and dumpster rental in Jefferson, GA. Flat pricing, same-week pickup. Serving the Jackson County seat and the I-85 growth corridor.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN JEFFERSON.',
    sub: 'Same-week hauling and driveway dumpsters across the Jackson County seat and the fast-growing I-85 corridor.',
    lakeContext: null,
    intro: 'Jefferson is the seat of Jackson County, a historic town, home of the first use of ether anesthesia, now growing fast along the I-85 corridor northeast of Atlanta. We haul junk and drop dumpsters across the area.',
    localAngle: 'Jefferson\u2019s rapid subdivision growth around the I-85 corridor, alongside its older in-town homes, keeps us busy with new-construction debris, move-ins and move-outs, remodels, and full household cleanouts.',
    areas: ['Downtown Jefferson', 'Traditions of Braselton (Jefferson)', 'I-85 corridor', 'US-129 / GA-11', 'Jackson County growth subdivisions'],
    disposal: 'Jefferson loads are handled through Jackson County\u2019s system, with the county transfer station on Landfill Drive in Jefferson. We donate and recycle what we can first.',
    distance: 'On the I-85 corridor in Jackson County, about 60 miles northeast of Atlanta.',
    faqs: [
      { q: 'Do you serve Jefferson and Jackson County?', a: 'Yes. Jefferson, the Jackson County seat, is in our service area, and we handle everything from single-item pickups to full cleanouts and dumpster rentals.' },
      { q: 'Can you handle new-construction debris in Jefferson?', a: 'We can. With Jefferson growing quickly along I-85, we clear construction and renovation debris both as full-service hauls and with roll-off dumpsters you load yourself.' },
      { q: 'Where does Jefferson junk get taken?', a: 'Trash is handled through Jackson County\u2019s system and the transfer station on Landfill Drive in Jefferson. Before that, we donate usable items and recycle metal and electronics.' },
    ],
    nearby: [{ slug: 'braselton', label: 'Braselton' }, { slug: 'hoschton', label: 'Hoschton' }, { slug: 'gainesville', label: 'Gainesville' }],
  },

  'hoschton': {
    slug: 'hoschton', name: 'Hoschton', countyLabel: 'Jackson County',
    region: 'North Georgia', zip: '30548',
    metaTitle: 'Junk Removal & Dumpster Rental in Hoschton, GA',
    metaDescription: 'Junk removal and dumpster rental in Hoschton, GA. Flat pricing, same-week pickup. From the Twin Lakes growth to the Chateau Elan side of Jackson County.',
    h1: 'JUNK REMOVAL & DUMPSTER RENTAL IN HOSCHTON.',
    sub: 'Same-week hauling and driveway dumpsters across the fast-growing Jackson County town near Chateau Elan.',
    lakeContext: null,
    intro: 'Hoschton is a small Jackson County town that has become one of the northeast metro\u2019s fastest-growing spots, anchored by large communities like Twin Lakes and neighboring the Chateau Elan side of Braselton. We haul junk and drop dumpsters throughout.',
    localAngle: 'Hoschton\u2019s wave of new master-planned and active-adult communities means constant move-ins, downsizing, and remodels, exactly the situations where a driveway dumpster or a quick furniture haul makes the difference.',
    areas: ['Twin Lakes', 'Del Webb / Cresswind Chateau Elan area', 'Reunion area', 'Downtown Hoschton', 'GA-53 corridor'],
    disposal: 'Hoschton loads are handled through Jackson County\u2019s system, with the county transfer station on Landfill Drive in Jefferson. We donate and recycle first.',
    distance: 'In southern Jackson County near Braselton, about 50 miles northeast of Atlanta.',
    faqs: [
      { q: 'Do you serve the Twin Lakes and Del Webb communities in Hoschton?', a: 'Yes. Hoschton\u2019s large master-planned and active-adult communities like Twin Lakes are a busy part of our area for downsizing hauls, furniture removal, and cleanouts.' },
      { q: 'Can you handle a downsizing cleanout in Hoschton?', a: 'We can. Downsizing and move-in cleanouts are common in Hoschton\u2019s newer communities. We do the lifting, set aside what you keep, and donate usable items.' },
      { q: 'Do you rent dumpsters in Hoschton?', a: 'Yes. Driveway roll-offs are popular for Hoschton remodels and cleanouts, sized to your project with flat pricing and tonnage set up front.' },
    ],
    nearby: [{ slug: 'braselton', label: 'Braselton' }, { slug: 'jefferson', label: 'Jefferson' }, { slug: 'buford', label: 'Buford' }],
  },
}

export const citySlugs = Object.keys(cities)
export const getCity = (slug) => cities[slug] || null
