// lib/junkServicesData.js
// Data source for the junk removal item + cleanout pages served by
// app/junk-removal/[slug]/page.js. Each entry is a genuinely distinct service
// with its own items, prep, disposal path, and price drivers, so no two pages
// read as near-duplicates. Add a service by adding an object here; the route
// and sitemap pick it up automatically.

export const junkServices = {
  'furniture-removal': {
    slug: 'furniture-removal',
    name: 'Furniture Removal',
    eyebrow: 'Junk removal service',
    h1: 'FURNITURE REMOVAL, DONE FOR YOU.',
    metaTitle: 'Furniture Removal in Gainesville & North Georgia',
    metaDescription: 'Same-week furniture removal in Gainesville and North Georgia. Couches, mattresses, dressers, and more. We do the lifting. Upfront flat pricing.',
    lede: 'That sectional will not fit down the stairs the same way it came up, and nobody wants to spend a Saturday fighting a sleeper sofa. Point at the piece and consider it gone.',
    intro: 'Furniture is one of the most common things we haul, and one of the most awkward to move alone. It is heavy, it snags on door frames, and most transfer stations will not take it curbside. We handle the whole job from wherever the piece sits, and we sort it for donation or recycling before anything heads to the landfill.',
    takeTitle: 'Furniture we take every week',
    take: [
      { name: 'Couches & sectionals', note: 'Sleeper sofas, loveseats, recliners, and oversized sectionals.' },
      { name: 'Mattresses & box springs', note: 'Any size, routed to mattress recyclers where we can.' },
      { name: 'Dressers & armoires', note: 'Solid wood, particle board, and mirrored pieces.' },
      { name: 'Tables & chairs', note: 'Dining sets, coffee tables, desks, and patio furniture.' },
      { name: 'Bed frames & headboards', note: 'Metal, wood, upholstered, and adjustable bases.' },
      { name: 'Entertainment centers', note: 'Big wall units and TV stands that take two people to lift.' },
    ],
    howTitle: 'How furniture removal works',
    how: [
      { n: '1', title: 'Send a photo', body: 'Text or upload a picture. We come back with a real, flat price.' },
      { n: '2', title: 'Pick your slot', body: 'Same-week and next-day windows across North Georgia.' },
      { n: '3', title: 'We haul it out', body: 'We carry it from wherever it sits and tidy the spot before we leave.' },
    ],
    priceNote: 'Furniture removal is priced by how much space it takes on the truck, not by guesswork. A single couch is usually a small flat fee, and a full room is priced by the load. You get the number up front.',
    donation: 'Gently used furniture rarely needs to become trash. We take pieces with life left in them to local donation centers around North Georgia, and we can get you a donation receipt for your taxes if you ask.',
    faqs: [
      { q: 'Do I need to move the furniture outside first?', a: 'No. We carry it out from wherever it sits, whether that is a second-floor bedroom or a walk-out basement. Leaving it in place is completely fine.' },
      { q: 'How much does it cost to remove a couch?', a: 'A single couch is usually a small flat fee, confirmed up front once we see a photo. Removing several pieces at once is priced by how much of the truck they fill, which almost always works out cheaper per item.' },
      { q: 'Can you take just one piece?', a: 'Yes. Single-item pickups are common and there is no minimum load. If you only need one dresser gone, we will come get the one dresser.' },
      { q: 'What happens to my old furniture?', a: 'We sort every load. Usable pieces go to local donation partners, metal and eligible materials go to recyclers, and only what is truly done heads to the landfill.' },
    ],
    related: [
      { href: '/junk-removal', label: 'All junk removal' },
      { href: '/junk-removal-cost', label: 'Junk removal pricing' },
      { href: '/junk-removal/mattress-removal', label: 'Mattress removal' },
    ],
  },

  'appliance-removal': {
    slug: 'appliance-removal',
    name: 'Appliance Removal',
    eyebrow: 'Junk removal service',
    h1: 'APPLIANCE REMOVAL & DISPOSAL.',
    metaTitle: 'Appliance Removal & Disposal in Gainesville & North Georgia',
    metaDescription: 'Washer, dryer, stove, or fridge hauled away across North Georgia. We disconnect, carry out, and recycle. Refrigerant handled to code. Flat pricing.',
    lede: 'A dead washer or an old stove is heavy, awkward, and full of metal that belongs at a recycler, not a curb. We take the whole thing off your hands.',
    intro: 'We remove and recycle household appliances of every kind. Metal-heavy machines like washers, dryers, and ranges are almost fully recyclable, so we route them to scrap and appliance recyclers instead of the landfill whenever possible. Refrigerant units get handled to code (more on that below).',
    takeTitle: 'Appliances we haul',
    take: [
      { name: 'Washers & dryers', note: 'Front-load, top-load, stacked, and pedestal units.' },
      { name: 'Stoves & ranges', note: 'Electric and gas, wall ovens, and cooktops.' },
      { name: 'Dishwashers', note: 'Built-in and portable, disconnected and carried out.' },
      { name: 'Microwaves & small appliances', note: 'Countertop and over-the-range units.' },
      { name: 'Water heaters', note: 'Tank and tankless, drained and hauled.' },
      { name: 'Refrigerators & freezers', note: 'Refrigerant recovered to code before recycling.' },
    ],
    howTitle: 'How appliance removal works',
    how: [
      { n: '1', title: 'Tell us the unit', body: 'Send a photo or the make. We quote a flat price on the spot.' },
      { n: '2', title: 'We disconnect', body: 'We handle the unhooking and the carry-out, upstairs or down.' },
      { n: '3', title: 'Recycled right', body: 'Metal to scrap, refrigerant to code, landfill last.' },
    ],
    priceNote: 'Appliance removal is a flat fee per unit, with a lower per-item price when we grab several at once. Refrigerant units may carry a small handling fee, and you hear that number before we start.',
    donation: 'Working appliances can find a second home. When a unit still runs, we offer it to local donation partners, and everything else gets stripped for metal recycling before anything is thrown away.',
    faqs: [
      { q: 'Do you take refrigerators and freezers with refrigerant?', a: 'Yes. Under EPA rules, refrigerant must be safely recovered before a fridge, freezer, or AC unit is disposed of, and the final disposer has to document it. We route these units to recyclers who recover the refrigerant properly, so it is handled to code, not dumped.' },
      { q: 'Do I need to disconnect the appliance first?', a: 'No. We handle the disconnect for standard hookups, including water lines on washers and dishwashers. If a unit is hardwired or on a gas line, let us know so we can plan for it.' },
      { q: 'How much does appliance removal cost?', a: 'It is a flat fee per unit, confirmed up front. Grabbing several appliances in one trip lowers the price per item, so it pays to clear them all at once.' },
      { q: 'Do you recycle old appliances?', a: 'Whenever we can. Washers, dryers, and ranges are mostly metal and go to scrap recyclers. Working units are offered for donation first. The goal is to keep them out of the landfill.' },
    ],
    related: [
      { href: '/junk-removal/refrigerator-disposal', label: 'Refrigerator disposal' },
      { href: '/junk-removal-cost', label: 'Junk removal pricing' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'mattress-removal': {
    slug: 'mattress-removal',
    name: 'Mattress Removal',
    eyebrow: 'Junk removal service',
    h1: 'MATTRESS REMOVAL & RECYCLING.',
    metaTitle: 'Mattress Removal & Disposal in Gainesville & North Georgia',
    metaDescription: 'Old mattress or box spring hauled off and recycled across North Georgia. No wrestling it downstairs. Flat price up front, same-week pickup.',
    lede: 'A mattress is the classic thing that will not fit in your car, will not go curbside, and will not bend around the stair rail. We take it, no gymnastics required.',
    intro: 'Mattresses are bulky, floppy, and banned or surcharged at many landfills, which is exactly why they pile up in garages and spare rooms. We haul any size and route them to mattress recyclers where the steel, foam, and fabric get separated and reused instead of buried.',
    takeTitle: 'What we take',
    take: [
      { name: 'Mattresses, any size', note: 'Twin through California king, memory foam or spring.' },
      { name: 'Box springs & foundations', note: 'Standard and low-profile.' },
      { name: 'Adjustable bases', note: 'Motorized frames disconnected and hauled.' },
      { name: 'Bed frames', note: 'Metal and wood, taken along with the mattress.' },
      { name: 'Crib & bunk mattresses', note: 'Smaller sizes are no problem.' },
      { name: 'Multiple sets', note: 'Clearing a rental or a whole house? We grab them all.' },
    ],
    howTitle: 'How mattress removal works',
    how: [
      { n: '1', title: 'Book a slot', body: 'Tell us how many and where. We quote a flat price fast.' },
      { n: '2', title: 'We carry it out', body: 'From any floor, no dragging it downstairs yourself.' },
      { n: '3', title: 'Recycled, not buried', body: 'Steel, foam, and fabric separated and reused where possible.' },
    ],
    priceNote: 'Mattress removal is a small flat fee per piece, and clearing a full set or several beds at once brings the per-item price down. The number is confirmed before we lift anything.',
    donation: 'Gently used, clean mattresses can sometimes be donated. When one does not qualify, we take it to a recycler so the components get a second life instead of a landfill spot.',
    faqs: [
      { q: 'How much does it cost to remove a mattress?', a: 'A single mattress is a small flat fee, confirmed up front. Removing a full set or several beds at once lowers the price per piece.' },
      { q: 'Do you recycle mattresses?', a: 'Yes, whenever possible. We route mattresses to recyclers who separate the steel springs, foam, and fabric for reuse, which keeps a bulky item out of the landfill.' },
      { q: 'Can you take the box spring and frame too?', a: 'Absolutely. We take the mattress, box spring, foundation, and the frame in one go, so the whole bed is gone in a single trip.' },
      { q: 'Do I have to move it outside?', a: 'No. We carry it out from the bedroom, upstairs or down. You do not need to touch it.' },
    ],
    related: [
      { href: '/junk-removal/furniture-removal', label: 'Furniture removal' },
      { href: '/junk-removal-cost', label: 'Junk removal pricing' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'refrigerator-disposal': {
    slug: 'refrigerator-disposal',
    name: 'Refrigerator Disposal',
    eyebrow: 'Junk removal service',
    h1: 'REFRIGERATOR & FREEZER DISPOSAL.',
    metaTitle: 'Refrigerator & Freezer Disposal in Gainesville & North Georgia',
    metaDescription: 'Old fridge or freezer hauled off and recycled to code across North Georgia. Refrigerant recovered under EPA rules. We handle the heavy lift.',
    lede: 'That garage backup fridge has been humming and hauling up your power bill for years. When it finally quits, we take it away and make sure the refrigerant is handled the right way.',
    intro: 'Refrigerators and freezers are not ordinary junk. They hold refrigerant that, under EPA Section 608 rules, has to be safely recovered before the unit can be disposed of, and the final disposer must document that it happened. We route every fridge and freezer to recyclers who recover the refrigerant properly, so you never have to worry about the legal side.',
    takeTitle: 'What we take',
    take: [
      { name: 'Refrigerators', note: 'Top and bottom freezer, side-by-side, French door.' },
      { name: 'Chest & upright freezers', note: 'Garage and basement backups included.' },
      { name: 'Mini fridges', note: 'Dorm and office units.' },
      { name: 'Wine & beverage coolers', note: 'Built-in and freestanding.' },
      { name: 'Ice makers', note: 'Standalone and under-counter.' },
      { name: 'Window AC units', note: 'Also hold refrigerant, handled the same way.' },
    ],
    howTitle: 'How refrigerator disposal works',
    how: [
      { n: '1', title: 'Point it out', body: 'Garage, kitchen, or basement, we come to the unit.' },
      { n: '2', title: 'We haul it out', body: 'Heavy and awkward is our job, not yours.' },
      { n: '3', title: 'Refrigerant to code', body: 'Recovered properly, then the metal gets recycled.' },
    ],
    priceNote: 'Refrigerator and freezer disposal is a flat fee per unit, which may include a small refrigerant handling charge. You hear the full number before we start.',
    donation: 'If a fridge still runs cold and clean, we will offer it for donation first. Otherwise the refrigerant is recovered and the steel and components are recycled.',
    faqs: [
      { q: 'Do you handle the freon or refrigerant?', a: 'Yes. EPA rules require refrigerant to be recovered before a fridge or freezer is disposed of, and the final disposer must document it. We route units to recyclers who recover it properly, so it is fully handled to code.' },
      { q: 'How much does it cost to remove a refrigerator?', a: 'It is a flat fee per unit, confirmed up front, which may include a small refrigerant handling charge. Adding other appliances to the same trip lowers your overall cost.' },
      { q: 'Do I need to empty or defrost it first?', a: 'Emptying it helps, and a quick defrost keeps things tidy, but it is not required. Just let us know if it is still cold so we can plan for any water.' },
      { q: 'Can you get it out of a basement or garage?', a: 'Yes. We handle stairs, tight doorways, and long carry-outs as part of the job, so a basement fridge is no problem.' },
    ],
    related: [
      { href: '/junk-removal/appliance-removal', label: 'Appliance removal' },
      { href: '/junk-removal-cost', label: 'Junk removal pricing' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'hot-tub-removal': {
    slug: 'hot-tub-removal',
    name: 'Hot Tub Removal',
    eyebrow: 'Junk removal service',
    h1: 'HOT TUB REMOVAL & DEMOLITION.',
    metaTitle: 'Hot Tub Removal & Demolition in Gainesville & North Georgia',
    metaDescription: 'Old hot tub or spa cut up and hauled off across North Georgia. We drain, disconnect, demolish, and clear the pad. Flat quote up front.',
    lede: 'A dead hot tub is one of the hardest things to get rid of on your own. It is heavy, waterlogged, and usually has to be cut apart to move. That is a normal Tuesday for us.',
    intro: 'Removing a hot tub is part demolition, part heavy lifting. We drain it, disconnect the power and water, cut it into manageable sections, and haul every piece away, leaving the pad or deck clear. Above-ground and in-ground spa shells both come out.',
    takeTitle: 'What the job covers',
    take: [
      { name: 'Draining', note: 'We empty the tub before we touch it.' },
      { name: 'Disconnecting', note: 'Power and water lines safely detached.' },
      { name: 'Demolition', note: 'Cut into sections that clear gates and tight yards.' },
      { name: 'Full haul-off', note: 'Shell, cabinet, cover, and equipment all gone.' },
      { name: 'Deck & pad clearing', note: 'The spot is left clean and ready.' },
      { name: 'Swim spas & large units', note: 'Bigger jobs welcome, quoted on sight.' },
    ],
    howTitle: 'How hot tub removal works',
    how: [
      { n: '1', title: 'Send photos', body: 'A shot of the tub and its access gets you a real quote.' },
      { n: '2', title: 'We demo it', body: 'Drain, disconnect, cut, and carry out through the yard.' },
      { n: '3', title: 'Clean finish', body: 'We clear the pad and haul every last piece.' },
    ],
    priceNote: 'Hot tub removal is quoted per job because size, access, and whether it needs cutting all matter. Send a couple of photos and we give you one flat number, demolition and haul-off included.',
    donation: 'Most hot tubs at the end of their life are not donatable, so we focus on recycling the metal frame and equipment and disposing of the shell responsibly.',
    faqs: [
      { q: 'How much does it cost to remove a hot tub?', a: 'Because size and access vary so much, we quote hot tubs per job. Send photos of the tub and the path out to the street and we give you one flat price with demolition and haul-off included.' },
      { q: 'Do you drain and disconnect it?', a: 'Yes. We drain the water, disconnect the power and plumbing, and break the tub down ourselves. You do not need to prep anything.' },
      { q: 'Can you get it out of a fenced backyard?', a: 'That is the most common scenario. We cut the tub into sections that fit through gates and around tight corners, so a fenced yard is not a problem.' },
      { q: 'Do you clean up after?', a: 'Always. We clear the pad or deck, sweep up the debris, and haul every piece, so you are left with an open, clean spot.' },
    ],
    related: [
      { href: '/junk-removal/shed-demolition', label: 'Shed & playset teardown' },
      { href: '/junk-removal-cost', label: 'Junk removal pricing' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'exercise-equipment-removal': {
    slug: 'exercise-equipment-removal',
    name: 'Exercise Equipment Removal',
    eyebrow: 'Junk removal service',
    h1: 'EXERCISE EQUIPMENT REMOVAL.',
    metaTitle: 'Treadmill & Exercise Equipment Removal in North Georgia',
    metaDescription: 'Treadmill, elliptical, or home gym hauled away across North Georgia. Heavy, bolted gear taken apart and carried out. Flat price, same-week pickup.',
    lede: 'A treadmill makes a great coat rack and a terrible thing to move. When the home gym becomes an obstacle course, we clear it out.',
    intro: 'Home exercise equipment is deceptively heavy and usually bolted together in a spare room or basement. We disassemble what needs it, carry the pieces out, and haul the whole setup, from a single treadmill to a full home gym.',
    takeTitle: 'Gear we haul',
    take: [
      { name: 'Treadmills', note: 'Folding and commercial-style decks.' },
      { name: 'Ellipticals & bikes', note: 'Cross-trainers, spin bikes, recumbents.' },
      { name: 'Weight benches & racks', note: 'Squat racks, Smith machines, power cages.' },
      { name: 'Free weights & plates', note: 'Dumbbell sets, plate trees, kettlebells.' },
      { name: 'Home gym systems', note: 'Cable machines and multi-station units.' },
      { name: 'Rowers & steppers', note: 'Any cardio piece taking up the room.' },
    ],
    howTitle: 'How it works',
    how: [
      { n: '1', title: 'Show us the gear', body: 'A photo and the room it is in gets a flat quote.' },
      { n: '2', title: 'We break it down', body: 'Disassembly and carry-out handled by us.' },
      { n: '3', title: 'Hauled and sorted', body: 'Metal recycled, working gear offered for donation.' },
    ],
    priceNote: 'Exercise equipment is priced by how much space it fills on the truck. One treadmill is a small flat fee, and a full home gym is priced by the load, always confirmed up front.',
    donation: 'Working equipment is worth passing on. We offer usable treadmills, benches, and weights to local donation partners, and the metal-heavy rest goes to recyclers.',
    faqs: [
      { q: 'Can you get a treadmill out of the basement?', a: 'Yes. Treadmills are heavy and awkward on stairs, which is exactly the job. We carry it up and out, and disassemble it first if that makes the path safer.' },
      { q: 'Do you take heavy weights and plates?', a: 'We do. Dumbbells, plates, and racks are dense but standard for us, and the metal is highly recyclable.' },
      { q: 'How much does it cost to remove a treadmill?', a: 'A single treadmill is a small flat fee confirmed up front. Clearing a whole home gym at once is priced by the load and works out cheaper per piece.' },
      { q: 'Do I need to take it apart first?', a: 'No. We handle any disassembly needed to get it out safely, so you can leave it standing.' },
    ],
    related: [
      { href: '/junk-removal/furniture-removal', label: 'Furniture removal' },
      { href: '/junk-removal/garage-cleanout', label: 'Garage cleanout' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'piano-removal': {
    slug: 'piano-removal',
    name: 'Piano Removal',
    eyebrow: 'Junk removal service',
    h1: 'PIANO REMOVAL & HAUL-OFF.',
    metaTitle: 'Piano Removal in Gainesville & North Georgia',
    metaDescription: 'Upright, console, or grand piano removed across North Georgia. Hundreds of pounds moved safely from any room. Flat quote, no damage to your home.',
    lede: 'A piano is one of the heaviest, most stubborn things in any home, often 300 to 900 pounds of iron and wood. Moving it is a job for a crew, not a favor from friends.',
    intro: 'Pianos are dense, top-heavy, and unforgiving on floors and door frames. We remove uprights, consoles, spinets, and grands, using the right gear and enough hands to get it out without gouging your walls or hurting anyone. When a piano is beyond saving, we haul it off for good.',
    takeTitle: 'Pianos we move',
    take: [
      { name: 'Upright & console', note: 'The most common home pianos.' },
      { name: 'Spinet pianos', note: 'Compact but still very heavy.' },
      { name: 'Baby grand & grand', note: 'Disassembled as needed for safe removal.' },
      { name: 'Player pianos', note: 'Extra weight from the mechanism, no problem.' },
      { name: 'Digital & console organs', note: 'Heavy electronic units too.' },
      { name: 'Upstairs pianos', note: 'Stairs and tight turns handled with care.' },
    ],
    howTitle: 'How piano removal works',
    how: [
      { n: '1', title: 'Send details', body: 'Type of piano and where it sits gets a flat quote.' },
      { n: '2', title: 'We move it safely', body: 'Right gear, enough hands, no damage to your home.' },
      { n: '3', title: 'Hauled for good', body: 'We take it away and clear the space.' },
    ],
    priceNote: 'Piano removal is quoted per job since weight, type, and stairs all matter. Tell us the piano and the path out, and we set one flat price with the heavy lifting included.',
    donation: 'A playable piano is worth saving. If yours still holds a tune, we can try to route it to someone who wants it. Beyond repair, it is broken down and the materials handled responsibly.',
    faqs: [
      { q: 'Can you remove a piano from upstairs?', a: 'Yes. Stairs are the hardest part of any piano move, and we plan for them with the right equipment and enough crew to do it safely without damaging your home.' },
      { q: 'How much does piano removal cost?', a: 'We quote pianos per job because an upstairs grand and a ground-floor upright are very different lifts. Send the type and location and you get one flat price up front.' },
      { q: 'Do you take grand pianos?', a: 'We do. Grands are disassembled as needed, the legs and lid removed, so the body can be moved safely and hauled away.' },
      { q: 'Will you protect my floors and walls?', a: 'Yes. We pad, protect, and plan the path so the piano comes out clean, with no scuffs or gouges left behind.' },
    ],
    related: [
      { href: '/junk-removal/furniture-removal', label: 'Furniture removal' },
      { href: '/junk-removal-cost', label: 'Junk removal pricing' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'tv-ewaste-disposal': {
    slug: 'tv-ewaste-disposal',
    name: 'TV & Electronics Disposal',
    eyebrow: 'Junk removal service',
    h1: 'TV & ELECTRONICS DISPOSAL.',
    metaTitle: 'TV & E-Waste Disposal in Gainesville & North Georgia',
    metaDescription: 'Old TVs, computers, and electronics hauled off and recycled across North Georgia. Heavy CRTs and flat screens included. Flat pricing, e-waste done right.',
    lede: 'Old electronics are not supposed to go in the regular trash, and that dusty tube TV in the closet weighs a ton. We take it and recycle it the right way.',
    intro: 'Electronics contain metals and materials that belong at an e-waste recycler, not a landfill. We haul TVs of every kind, from heavy old CRTs to big flat screens, plus computers, printers, and the tangle of gear that piles up in closets and offices, and route it to responsible recyclers.',
    takeTitle: 'Electronics we take',
    take: [
      { name: 'Flat screen TVs', note: 'LED, LCD, and plasma, any size.' },
      { name: 'CRT & tube TVs', note: 'The heavy old ones we all dread lifting.' },
      { name: 'Computers & monitors', note: 'Desktops, laptops, and displays.' },
      { name: 'Printers & scanners', note: 'Home and office units.' },
      { name: 'Stereo & AV gear', note: 'Receivers, speakers, and consoles.' },
      { name: 'Cables & accessories', note: 'The whole junk-drawer tangle.' },
    ],
    howTitle: 'How e-waste disposal works',
    how: [
      { n: '1', title: 'Gather it up', body: 'Point us to the pile or the room and we quote it.' },
      { n: '2', title: 'We haul it out', body: 'Heavy TVs and full setups carried out for you.' },
      { n: '3', title: 'Recycled right', body: 'Routed to responsible e-waste recyclers.' },
    ],
    priceNote: 'Electronics are priced by volume, with a small per-item minimum on TVs since they need special recycling. Clearing several items at once brings the price down, confirmed up front.',
    donation: 'Working electronics can be donated or reused. Everything else goes to certified e-waste recyclers so the metals and materials are recovered instead of buried.',
    faqs: [
      { q: 'Do you take old tube (CRT) TVs?', a: 'Yes. Those heavy old CRTs are exactly the thing people struggle to get rid of. We carry them out and route them to e-waste recyclers equipped to handle them.' },
      { q: 'How do you dispose of electronics?', a: 'We send electronics to responsible e-waste recyclers who recover the metals and materials. Many electronics are restricted from regular landfills, so this keeps you on the right side of disposal rules.' },
      { q: 'Can you wipe my data first?', a: 'We recommend wiping or removing hard drives before pickup for your own security. We can set devices aside for you to pull drives if you like.' },
      { q: 'How much does TV disposal cost?', a: 'TVs carry a small per-item fee because of the special recycling involved, confirmed up front. Adding other electronics to the same trip lowers the overall cost.' },
    ],
    related: [
      { href: '/junk-removal/appliance-removal', label: 'Appliance removal' },
      { href: '/junk-removal/garage-cleanout', label: 'Garage cleanout' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'garage-cleanout': {
    slug: 'garage-cleanout',
    name: 'Garage Cleanout',
    eyebrow: 'Junk removal service',
    h1: 'GARAGE CLEANOUTS, START TO FINISH.',
    metaTitle: 'Garage Cleanout Services in Gainesville & North Georgia',
    metaDescription: 'Reclaim your garage across North Georgia. We haul furniture, tools, and years of clutter, then sweep up. Park in there again. Flat pricing by the load.',
    lede: 'The garage is where everything goes to be dealt with later, and later never comes. We clear it in an afternoon so you can actually park in there again.',
    intro: 'A garage cleanout is really a dozen small removals at once: old furniture, broken tools, boxes nobody opened, paint cans, busted holiday decorations. We sort it, haul what goes, set aside anything you want to keep, and sweep the floor when we are done.',
    takeTitle: 'What we clear out',
    take: [
      { name: 'Old furniture & boxes', note: 'The stuff that migrated out of the house.' },
      { name: 'Broken tools & gear', note: 'Dead power tools, rusted hand tools, spare parts.' },
      { name: 'Bikes & sporting goods', note: 'Outgrown or outworn.' },
      { name: 'Holiday & seasonal clutter', note: 'Cracked totes and tangled lights.' },
      { name: 'Scrap metal & lumber', note: 'Leftover project materials.' },
      { name: 'General junk', note: 'Whatever piled up over the years.' },
    ],
    howTitle: 'How a garage cleanout works',
    how: [
      { n: '1', title: 'Walk us through it', body: 'Point out what stays and what goes. We quote the load.' },
      { n: '2', title: 'We clear it', body: 'Sorting, lifting, and loading, all handled.' },
      { n: '3', title: 'Swept clean', body: 'We leave the floor clear and ready to use.' },
    ],
    priceNote: 'Garage cleanouts are priced by how much fills the truck, from a quarter load to a full one. You get a flat number up front once we see the space or a few photos.',
    donation: 'Plenty of garage clutter still has value. Usable tools, furniture, and gear are set aside for donation, and metal and materials are recycled before anything hits the landfill.',
    faqs: [
      { q: 'How much does a garage cleanout cost?', a: 'It is priced by how much of the truck the load fills, usually somewhere between a half and a full load for a typical garage. You get a flat number up front after we see it or a few photos.' },
      { q: 'Do I need to sort everything first?', a: 'No. Just point out anything you want to keep and we handle the rest, including the sorting. We can also work alongside you if you would rather decide as we go.' },
      { q: 'Can you do it in one visit?', a: 'Most garages are a single-visit job. Larger or packed-to-the-rafters spaces might take a bit longer, and we will tell you up front what to expect.' },
      { q: 'Do you sweep up after?', a: 'Yes. We clear the floor and sweep, so you walk into an open, usable garage, not a half-finished job.' },
    ],
    related: [
      { href: '/junk-removal/estate-cleanout', label: 'Estate cleanout' },
      { href: '/dumpster-rental/cleanout-dumpster', label: 'Cleanout dumpster' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'estate-cleanout': {
    slug: 'estate-cleanout',
    name: 'Estate Cleanout',
    eyebrow: 'Junk removal service',
    h1: 'ESTATE CLEANOUTS, HANDLED WITH CARE.',
    metaTitle: 'Estate Cleanout Services in Gainesville & North Georgia',
    metaDescription: 'Compassionate, full-service estate cleanouts across North Georgia. We clear the whole home, donate what we can, and treat it with respect. Flat pricing.',
    lede: 'Clearing a loved one\u2019s home is heavy in every sense. We take the physical weight off your shoulders and handle the whole house with patience and respect.',
    intro: 'An estate cleanout means emptying an entire home, often during a hard time. We move at your pace, set aside anything you want to keep or pass on, donate usable belongings to local charities, and clear everything else so the house is ready to sell or hand over. You should not have to carry this alone.',
    takeTitle: 'What an estate cleanout covers',
    take: [
      { name: 'Whole-home clearing', note: 'Every room, closet, attic, and basement.' },
      { name: 'Furniture & belongings', note: 'Sorted for keep, donate, or haul.' },
      { name: 'Appliances', note: 'Removed and recycled, refrigerant to code.' },
      { name: 'Garage & shed', note: 'Tools, mowers, and outdoor clutter.' },
      { name: 'Donation coordination', note: 'Usable items routed to local charities.' },
      { name: 'Final sweep', note: 'The home left broom-clean and ready.' },
    ],
    howTitle: 'How an estate cleanout works',
    how: [
      { n: '1', title: 'We walk it together', body: 'You show us what matters. We plan around it.' },
      { n: '2', title: 'We clear the home', body: 'Room by room, at a pace that respects the moment.' },
      { n: '3', title: 'Donated & swept', body: 'Usable items donated, the house left clean.' },
    ],
    priceNote: 'Estate cleanouts are quoted per home based on size and volume. We walk it with you first, then set one flat price so there are no surprises during an already difficult time.',
    donation: 'We treat belongings with respect. Usable furniture, housewares, and clothing are donated to local North Georgia charities, and we can provide donation receipts for the estate.',
    faqs: [
      { q: 'How much does an estate cleanout cost?', a: 'We quote estate cleanouts per home after walking through it, based on the size of the house and how much needs to be cleared. You get one flat price up front, with no add-ons later.' },
      { q: 'Can you set aside items the family wants to keep?', a: 'Always. Before anything moves, you tell us what to keep or pass on, and we set those items aside carefully. Nothing leaves without your say-so.' },
      { q: 'Do you donate usable belongings?', a: 'Yes. We route usable furniture, housewares, and clothing to local charities and can provide donation receipts for the estate, so good items find a new home.' },
      { q: 'How quickly can you do it?', a: 'We work on your timeline, whether that means a single day or spreading it across a few visits. Just tell us the deadline for the sale or handover and we plan around it.' },
    ],
    related: [
      { href: '/junk-removal/hoarding-cleanout', label: 'Hoarding cleanout' },
      { href: '/junk-removal/eviction-cleanout', label: 'Eviction cleanout' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'hoarding-cleanout': {
    slug: 'hoarding-cleanout',
    name: 'Hoarding Cleanout',
    eyebrow: 'Junk removal service',
    h1: 'HOARDING CLEANOUTS, JUDGMENT-FREE.',
    metaTitle: 'Hoarding Cleanout Services in Gainesville & North Georgia',
    metaDescription: 'Discreet, judgment-free hoarding cleanouts across North Georgia. We clear the home safely at a pace that works for the family. Full discretion, flat rate.',
    lede: 'A hoarding situation is overwhelming to face and even harder to clear alone. We come in without judgment, work carefully, and help make a home livable again.',
    intro: 'Hoarding cleanouts take patience, sensitivity, and discretion, and we bring all three. We work with families and individuals to clear a home safely, watching for anything valuable or meaningful buried in the clutter, and we go at a pace that keeps everyone comfortable. Every job is confidential.',
    takeTitle: 'What we handle',
    take: [
      { name: 'Deep clutter clearing', note: 'Floor to ceiling, room by room.' },
      { name: 'Careful sorting', note: 'We watch for valuables, documents, and keepsakes.' },
      { name: 'Furniture & appliances', note: 'Removed and recycled as we clear.' },
      { name: 'Trash & spoiled items', note: 'Handled safely and hauled out.' },
      { name: 'Donation of usable goods', note: 'Good items routed to charity.' },
      { name: 'A livable finish', note: 'The home cleared and swept.' },
    ],
    howTitle: 'How a hoarding cleanout works',
    how: [
      { n: '1', title: 'A private plan', body: 'We talk through the home and set a comfortable pace.' },
      { n: '2', title: 'Careful clearing', body: 'We sort as we go, watching for what matters.' },
      { n: '3', title: 'A fresh start', body: 'The space cleared, cleaned, and livable again.' },
    ],
    priceNote: 'Hoarding cleanouts are quoted per home after a private walkthrough, based on volume and conditions. You get one flat price and complete discretion, start to finish.',
    donation: 'We look for the good in every load. Usable belongings are set aside for donation, and we handle the rest respectfully, with the family in the loop the whole way.',
    faqs: [
      { q: 'Is the cleanout confidential?', a: 'Completely. We handle every hoarding job with discretion, no signage drama and no judgment. What happens at the home stays between us and the family.' },
      { q: 'Will you look for valuables and important papers?', a: 'Yes. We sort carefully as we clear, watching for cash, documents, keepsakes, and anything meaningful, and we set those items aside for you.' },
      { q: 'How much does a hoarding cleanout cost?', a: 'We quote per home after a private walkthrough, based on how much is there and the conditions inside. You get one flat price up front, with no surprises.' },
      { q: 'Can you work at our pace?', a: 'Absolutely. These situations are emotional, and we never rush. We can do it in one push or spread it across visits, whatever keeps everyone comfortable.' },
    ],
    related: [
      { href: '/junk-removal/estate-cleanout', label: 'Estate cleanout' },
      { href: '/junk-removal/eviction-cleanout', label: 'Eviction cleanout' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'eviction-cleanout': {
    slug: 'eviction-cleanout',
    name: 'Eviction Cleanout',
    eyebrow: 'Junk removal service',
    h1: 'EVICTION & FORECLOSURE CLEANOUTS.',
    metaTitle: 'Eviction & Foreclosure Cleanout Services in North Georgia',
    metaDescription: 'Fast property cleanouts for landlords and agents across North Georgia. We clear left-behind belongings and trash so you can turn the unit. Flat pricing.',
    lede: 'A tenant left and so did any interest in packing. When a unit is full of what got left behind, we clear it fast so you can turn it and get it earning again.',
    intro: 'Eviction and foreclosure cleanouts are about speed and a clean slate. We clear left-behind furniture, trash, and belongings from houses, apartments, and rentals, so landlords, property managers, and agents can get a unit rent-ready or market-ready without the delay. Same-week and rush turnarounds are our specialty.',
    takeTitle: 'What we clear',
    take: [
      { name: 'Left-behind furniture', note: 'Whatever the last tenant abandoned.' },
      { name: 'Trash & debris', note: 'Bagged garbage, loose mess, spoiled food.' },
      { name: 'Appliances', note: 'Broken or abandoned units removed.' },
      { name: 'Personal belongings', note: 'Cleared per your instructions and local rules.' },
      { name: 'Garage, patio & storage', note: 'Every corner of the unit.' },
      { name: 'A rent-ready finish', note: 'Emptied and swept for the next tenant.' },
    ],
    howTitle: 'How an eviction cleanout works',
    how: [
      { n: '1', title: 'Send the address', body: 'Photos or a walkthrough get you a fast quote.' },
      { n: '2', title: 'We clear it out', body: 'Full unit emptied, often same week.' },
      { n: '3', title: 'Turn it fast', body: 'Swept and ready to re-list or re-rent.' },
    ],
    priceNote: 'Eviction cleanouts are priced by volume, from a single room to a whole house. We move fast and give you a flat quote up front so you can budget the turn.',
    donation: 'Even in a cleanout, usable furniture and goods get offered for donation before disposal, and recyclable materials are pulled out, so the job is done responsibly as well as fast.',
    faqs: [
      { q: 'How fast can you clear a unit?', a: 'Speed is the point. We offer same-week and rush turnarounds so you can re-list or re-rent quickly. Tell us your deadline and we work to it.' },
      { q: 'How much does an eviction cleanout cost?', a: 'It is priced by how much needs clearing, from a single room to a full house. You get a flat quote up front, which makes it easy to fold into your turn budget.' },
      { q: 'Do you work with landlords and property managers?', a: 'Constantly. Landlords, property managers, agents, and REO teams are a big part of what we do, and we can coordinate access and handle recurring turns.' },
      { q: 'What about the tenant\u2019s belongings?', a: 'We clear per your instructions and local requirements. If items need to be set aside or handled a certain way, just tell us and we follow your direction.' },
    ],
    related: [
      { href: '/junk-removal/estate-cleanout', label: 'Estate cleanout' },
      { href: '/junk-removal/trash-removal', label: 'Trash removal' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'construction-debris-removal': {
    slug: 'construction-debris-removal',
    name: 'Construction Debris Removal',
    eyebrow: 'Junk removal service',
    h1: 'CONSTRUCTION DEBRIS REMOVAL.',
    metaTitle: 'Construction Debris Removal in Gainesville & North Georgia',
    metaDescription: 'Jobsite and remodel debris hauled off across North Georgia. Drywall, lumber, flooring, and demo waste cleared fast. Flat pricing or a dumpster, your call.',
    lede: 'A remodel makes a mountain of debris, and a cluttered jobsite slows everything down. We haul the mess so your crew can keep building.',
    intro: 'Construction and renovation projects generate heavy, bulky waste: torn-out drywall, old flooring, scrap lumber, cabinets, and demo debris. We clear it from the site so the work keeps moving, either as a full-service haul where we do the loading, or paired with a dumpster if you would rather load as you go.',
    takeTitle: 'Debris we haul',
    take: [
      { name: 'Drywall & plaster', note: 'Torn-out walls and ceilings.' },
      { name: 'Lumber & framing scrap', note: 'Offcuts, old studs, and trim.' },
      { name: 'Flooring & carpet', note: 'Tile, hardwood, laminate, and pad.' },
      { name: 'Cabinets & fixtures', note: 'Ripped-out kitchens and baths.' },
      { name: 'Roofing & siding', note: 'Tear-off shingles and old siding.' },
      { name: 'General demo debris', note: 'The pile that builds up fast.' },
    ],
    howTitle: 'How debris removal works',
    how: [
      { n: '1', title: 'Tell us the job', body: 'Site, materials, and volume get you a quote.' },
      { n: '2', title: 'We clear it', body: 'Full-service haul, or drop a dumpster to load.' },
      { n: '3', title: 'Keep moving', body: 'A clean site so the crew stays productive.' },
    ],
    priceNote: 'Debris removal is priced by volume and weight, since materials like tile and shingles are dense. You get a flat quote up front, and we will tell you honestly whether a haul or a dumpster costs you less.',
    donation: 'Reusable materials like cabinets, doors, and fixtures can sometimes be donated to building-reuse centers. Metal is recycled, and clean fill is handled separately from general debris.',
    faqs: [
      { q: 'Do you haul heavy debris like tile and shingles?', a: 'Yes, and because those materials are dense, we price by weight as well as volume and set your allowance up front. For heavy debris, a smaller dumpster or a full-service haul is often the smarter call, and we will tell you which.' },
      { q: 'Should I rent a dumpster or book a haul?', a: 'If debris piles up over a multi-day job, a dumpster you load yourself is often cheaper. If you want it gone in one clean sweep with no loading, a full-service haul wins. We do both, so we will point you to the cheaper option.' },
      { q: 'Can you clear the site same week?', a: 'Usually yes. We keep jobsites moving with same-week and next-day pickups, and we can set up recurring hauls for longer projects.' },
      { q: 'What cannot go in a construction haul?', a: 'Hazardous materials like asbestos, wet paint, solvents, and chemicals cannot go in a standard haul or dumpster. If you are unsure about a material, ask us and we will point you to the right disposal.' },
    ],
    related: [
      { href: '/dumpster-rental/renovation-dumpster', label: 'Renovation dumpster' },
      { href: '/dumpster-rental/concrete-dumpster', label: 'Concrete & heavy debris' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'yard-debris-removal': {
    slug: 'yard-debris-removal',
    name: 'Yard Debris Removal',
    eyebrow: 'Junk removal service',
    h1: 'YARD & STORM DEBRIS REMOVAL.',
    metaTitle: 'Yard Waste & Storm Debris Removal in North Georgia',
    metaDescription: 'Branches, brush, and storm debris hauled off across North Georgia. After a storm or big yard project, we clear the mess. Flat pricing, fast pickup.',
    lede: 'A big yard project or a rough storm leaves a pile of branches and brush that will not fit in the green bin. We haul it all so you get your yard back.',
    intro: 'Yard cleanups and North Georgia storms generate more debris than curbside pickup can handle. We clear fallen limbs, brush piles, old landscaping, and the leftovers from tree work and yard projects, hauling it away so you are not stuck with a pile for weeks.',
    takeTitle: 'Yard waste we clear',
    take: [
      { name: 'Branches & limbs', note: 'Storm-downed and trimmed.' },
      { name: 'Brush & shrubs', note: 'Cleared hedges and overgrowth.' },
      { name: 'Leaves & yard bags', note: 'Piles too big for the curb.' },
      { name: 'Old landscaping', note: 'Timbers, edging, and pulled plants.' },
      { name: 'Fencing & lattice', note: 'Rotted or storm-damaged sections.' },
      { name: 'Tree-work leftovers', note: 'Cut logs and stump debris.' },
    ],
    howTitle: 'How yard debris removal works',
    how: [
      { n: '1', title: 'Show us the pile', body: 'A photo of the debris gets a quick quote.' },
      { n: '2', title: 'We load it up', body: 'Branches, brush, and bags hauled by hand.' },
      { n: '3', title: 'Yard restored', body: 'The mess gone, the yard usable again.' },
    ],
    priceNote: 'Yard debris is priced by how much fills the truck. A few brush piles is a small load, and a full storm cleanup is priced accordingly, always quoted up front.',
    donation: 'Clean yard waste is routed to green-waste and mulching facilities where possible, so limbs and brush are turned into mulch instead of taking up landfill space.',
    faqs: [
      { q: 'Do you haul storm debris?', a: 'Yes. After a North Georgia storm, we clear fallen limbs, downed branches, and the debris that curbside pickup will not take, so your yard is safe and usable again fast.' },
      { q: 'How much does yard debris removal cost?', a: 'It is priced by how much of the truck the debris fills. A couple of brush piles is a small load, while a full storm cleanup is larger, and you get a flat quote up front either way.' },
      { q: 'Do you take logs and tree-work leftovers?', a: 'We do. Cut logs, limbs, and stump debris from tree work are common loads for us, hauled by hand and taken away.' },
      { q: 'What about dirt and rocks?', a: 'Clean yard waste like brush and limbs is straightforward. Heavy materials like dirt, rock, and concrete are handled differently, often better suited to a dumpster, so let us know and we will size it right.' },
    ],
    related: [
      { href: '/dumpster-rental/yard-waste-dumpster', label: 'Yard waste dumpster' },
      { href: '/junk-removal/shed-demolition', label: 'Shed & playset teardown' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'shed-demolition': {
    slug: 'shed-demolition',
    name: 'Shed & Playset Teardown',
    eyebrow: 'Junk removal service',
    h1: 'SHED, PLAYSET & TRAMPOLINE TEARDOWN.',
    metaTitle: 'Shed, Playset & Trampoline Removal in North Georgia',
    metaDescription: 'Old sheds, swing sets, trampolines, and decks torn down and hauled off across North Georgia. We demo it and clear the spot. Flat quote up front.',
    lede: 'The kids outgrew the swing set, the shed is falling over, and the trampoline has not bounced in years. We tear it down and haul it off in one visit.',
    intro: 'Outdoor structures are a two-part job: demolition, then haul-off. We take down old sheds, wooden and metal swing sets, trampolines, playhouses, and small decks, cut the material to size, and clear every piece, leaving a clean, open spot in the yard.',
    takeTitle: 'What we tear down',
    take: [
      { name: 'Storage sheds', note: 'Wood, metal, and resin, taken to the slab.' },
      { name: 'Swing sets & playsets', note: 'Wooden forts and metal sets.' },
      { name: 'Trampolines', note: 'Disassembled and hauled, frame and all.' },
      { name: 'Playhouses', note: 'Kid-sized structures cleared out.' },
      { name: 'Small decks', note: 'Rotted or unwanted platforms.' },
      { name: 'Fencing & pergolas', note: 'Old sections and freestanding structures.' },
    ],
    howTitle: 'How teardown works',
    how: [
      { n: '1', title: 'Send photos', body: 'The structure and its access get you a quote.' },
      { n: '2', title: 'We demo it', body: 'Taken apart safely and cut down to haul.' },
      { n: '3', title: 'Spot cleared', body: 'Every piece removed, the ground left open.' },
    ],
    priceNote: 'Teardowns are quoted per structure since size and construction vary. Send photos and we set one flat price with the demolition and haul-off included.',
    donation: 'When a shed or playset is still in good shape, we can sometimes route it for reuse. Otherwise wood is disposed of responsibly and the metal is recycled.',
    faqs: [
      { q: 'Do you demolish the structure or just haul it?', a: 'Both. We tear it down and haul it away in the same visit, so you do not have to demo it yourself first. Just point at the shed or playset and we handle the rest.' },
      { q: 'Can you remove a trampoline?', a: 'Yes. We disassemble the trampoline, frame, springs, and mat, and haul the whole thing, so you are not left wrestling with rusted bolts.' },
      { q: 'How much does shed removal cost?', a: 'We quote per structure because a small metal shed and a large wooden one are different jobs. Send a few photos and you get one flat price, demolition included.' },
      { q: 'Will the yard be a mess after?', a: 'No. We clear every piece of debris and leave the spot open and clean, ready for whatever is next, grass, a new structure, or open space.' },
    ],
    related: [
      { href: '/junk-removal/hot-tub-removal', label: 'Hot tub removal' },
      { href: '/junk-removal/yard-debris-removal', label: 'Yard debris removal' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },

  'trash-removal': {
    slug: 'trash-removal',
    name: 'Trash Removal',
    eyebrow: 'Junk removal service',
    h1: 'TRASH & JUNK REMOVAL, ANY AMOUNT.',
    metaTitle: 'Trash & Junk Removal in Gainesville & North Georgia',
    metaDescription: 'Piled-up trash, basement junk, and clutter hauled away across North Georgia. From one load to a whole house, we clear it and sweep up. Flat pricing.',
    lede: 'Sometimes it is not one big thing, it is a pile of everything. Bags, boxes, odds and ends, and clutter that never made it to the curb. We take all of it.',
    intro: 'General trash and junk removal is our bread and butter: the accumulation that fills a basement, a spare room, or the back of a garage. We haul household junk, bagged trash, and mixed clutter of every kind, sort out what can be donated or recycled, and leave the space clean.',
    takeTitle: 'What we haul',
    take: [
      { name: 'Bagged household trash', note: 'Piles too big for regular pickup.' },
      { name: 'Basement & attic clutter', note: 'Years of stored odds and ends.' },
      { name: 'Boxes & packing', note: 'Move-in and move-out leftovers.' },
      { name: 'Broken household items', note: 'Whatever finally gave out.' },
      { name: 'Mixed junk piles', note: 'A little of everything, all at once.' },
      { name: 'Small remodel leftovers', note: 'The odds and ends after a project.' },
    ],
    howTitle: 'How trash removal works',
    how: [
      { n: '1', title: 'Point at the pile', body: 'A photo or walkthrough gets a flat quote.' },
      { n: '2', title: 'We load it all', body: 'Every bag and box, from any room.' },
      { n: '3', title: 'Clean space', body: 'Hauled off and swept, donation and recycling first.' },
    ],
    priceNote: 'Trash and junk removal is priced by how much fills the truck, from a single item to a full load. You always get a flat number up front, no per-bag guessing.',
    donation: 'Even in a trash haul, we pull out anything usable for donation and recycle metal, cardboard, and electronics, so the landfill is the last stop, not the first.',
    faqs: [
      { q: 'Is there a minimum amount for pickup?', a: 'No minimum. Whether it is one item or a full basement, we will come get it, and larger loads simply cost less per item.' },
      { q: 'How much does junk removal cost?', a: 'It is priced by how much of the truck your load fills, confirmed as a flat number up front. Our full pricing guide breaks down single items through full truckloads.' },
      { q: 'Do you carry it out, or does it need to be at the curb?', a: 'We carry it out from wherever it sits, any room, any floor. You do not need to drag anything to the curb first.' },
      { q: 'What happens to it after?', a: 'We sort every load. Usable items go to donation, metal and cardboard and electronics go to recyclers, and only the true trash heads to the landfill.' },
    ],
    related: [
      { href: '/junk-removal-cost', label: 'Junk removal pricing' },
      { href: '/junk-removal/garage-cleanout', label: 'Garage cleanout' },
      { href: '/junk-removal', label: 'All junk removal' },
    ],
  },
}

export const junkServiceSlugs = Object.keys(junkServices)
export const getJunkService = (slug) => junkServices[slug] || null
